language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm

before_install:
    - composer self-update

install:
    - composer install --prefer-dist

script:
    - composer test

after_script:
    - php ./vendor/bin/coveralls -v
